/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.7 */

#include "cc1101.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(cc11011_Message, cc11011_Message, AUTO)


PB_BIND(cc11011_SyncWord, cc11011_SyncWord, AUTO)


PB_BIND(cc11011_Node, cc11011_Node, AUTO)


PB_BIND(cc11011_Signal, cc11011_Signal, AUTO)








